apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-agent
  namespace: email-app
  labels:
    app: email-agent
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-agent
  template:
    metadata:
      labels:
        app: email-agent
        tier: backend
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command: ['sh', '-c', 'until nc -z postgres 5432; do echo waiting for db; sleep 2; done;']
      containers:
        - name: email-agent
          image: email-agent:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 7860
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: db-secret
          readinessProbe:
            httpGet:
              path: /
              port: 7860
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 7860
            initialDelaySeconds: 20
            periodSeconds: 10
