apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: email-app
  labels:
    app: email-agent
type: Opaque
stringData:
  POSTGRES_USER: email_user
  POSTGRES_PASSWORD: email_password
  POSTGRES_DB: email_db
  HUGGING_FACE_TOKEN: your_token_right_here